// <auto-generated />
using System;
using AE.Persistence.DatabaseContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AE.Persistence.Migrations
{
    [DbContext(typeof(AEDatabaseContext))]
    [Migration("20241203073410_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("AE.Domain.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Ports");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6029),
                            Latitude = 31.230399999999999,
                            Longitude = 121.47369999999999,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6040),
                            Name = "Port of Shanghai"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6042),
                            Latitude = 1.3521000000000001,
                            Longitude = 103.8198,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6043),
                            Name = "Port of Singapore"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6044),
                            Latitude = 29.868300000000001,
                            Longitude = 121.544,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6045),
                            Name = "Port of Ningbo-Zhoushan"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6046),
                            Latitude = 22.543099999999999,
                            Longitude = 114.0579,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6047),
                            Name = "Port of Shenzhen"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6048),
                            Latitude = 23.129100000000001,
                            Longitude = 113.26439999999999,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6049),
                            Name = "Port of Guangzhou"
                        },
                        new
                        {
                            Id = 6,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6050),
                            Latitude = 35.179600000000001,
                            Longitude = 129.07560000000001,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6051),
                            Name = "Port of Busan"
                        },
                        new
                        {
                            Id = 7,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6052),
                            Latitude = 22.319299999999998,
                            Longitude = 114.1694,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6053),
                            Name = "Port of Hong Kong"
                        },
                        new
                        {
                            Id = 8,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6054),
                            Latitude = 36.067100000000003,
                            Longitude = 120.3826,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6055),
                            Name = "Port of Qingdao"
                        },
                        new
                        {
                            Id = 9,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6056),
                            Latitude = 39.343400000000003,
                            Longitude = 117.3616,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6057),
                            Name = "Port of Tianjin"
                        },
                        new
                        {
                            Id = 10,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6058),
                            Latitude = 51.922499999999999,
                            Longitude = 4.4791999999999996,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6059),
                            Name = "Port of Rotterdam"
                        },
                        new
                        {
                            Id = 11,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6060),
                            Latitude = 25.067399999999999,
                            Longitude = 55.1372,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6061),
                            Name = "Port of Jebel Ali"
                        },
                        new
                        {
                            Id = 12,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6062),
                            Latitude = 53.551099999999998,
                            Longitude = 9.9937000000000005,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6062),
                            Name = "Port of Hamburg"
                        },
                        new
                        {
                            Id = 13,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6064),
                            Latitude = 51.260199999999998,
                            Longitude = 4.4028,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6065),
                            Name = "Port of Antwerp"
                        },
                        new
                        {
                            Id = 14,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6066),
                            Latitude = 33.740499999999997,
                            Longitude = -118.2727,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6067),
                            Name = "Port of Los Angeles"
                        },
                        new
                        {
                            Id = 15,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6068),
                            Latitude = 33.770099999999999,
                            Longitude = -118.19370000000001,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6069),
                            Name = "Port of Long Beach"
                        },
                        new
                        {
                            Id = 16,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6070),
                            Latitude = 1.3622000000000001,
                            Longitude = 103.56829999999999,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6070),
                            Name = "Port of Tanjung Pelepas"
                        },
                        new
                        {
                            Id = 17,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6072),
                            Latitude = 22.627300000000002,
                            Longitude = 120.3014,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6072),
                            Name = "Port of Kaohsiung"
                        },
                        new
                        {
                            Id = 18,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6073),
                            Latitude = 51.963999999999999,
                            Longitude = 1.3513999999999999,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6074),
                            Name = "Port of Felixstowe"
                        },
                        new
                        {
                            Id = 19,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6075),
                            Latitude = 36.140799999999999,
                            Longitude = -5.4561999999999999,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6076),
                            Name = "Port of Algeciras"
                        },
                        new
                        {
                            Id = 20,
                            CreatedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6077),
                            Latitude = 35.4437,
                            Longitude = 139.63800000000001,
                            ModifiedAt = new DateTime(2024, 12, 3, 14, 34, 10, 593, DateTimeKind.Local).AddTicks(6078),
                            Name = "Port of Yokohama"
                        });
                });

            modelBuilder.Entity("AE.Domain.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Velocity")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Ships");
                });

            modelBuilder.Entity("AE.Domain.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ModifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ShipUser", b =>
                {
                    b.Property<int>("ShipsId")
                        .HasColumnType("int");

                    b.Property<int>("UsersId")
                        .HasColumnType("int");

                    b.HasKey("ShipsId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("ShipUser");
                });

            modelBuilder.Entity("ShipUser", b =>
                {
                    b.HasOne("AE.Domain.Ship", null)
                        .WithMany()
                        .HasForeignKey("ShipsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AE.Domain.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
